### PR TITLE
add :name metadata via helper functions and use metadata for var names

### PR DESCRIPTION
**Pull request by bobisageek**
This PR got a little bigger than I wanted, but it includes some things that babashka will need for some var name cleanup.

**Background/problem statement**
The `sym` field on `SciVar`s sometimes contains a namespace, and sometimes doesn't. This can lead to unusual var name strings. In addition, some `SciVar`s currently don't get `:name` metadata (see https://github.com/babashka/babashka/issues/1223), which can lead to unexpected output from things like `doc` that use that metadata. Finally, some vars that get copied from clojure namespaces into sci namespaces are desired to have different names in sci, but copy-var always uses the name from the clojure namespace (on the var, not the sci namespace symbol). The anomalies that arise from this are primarily (entirely?) cosmetic in nature.

Examples (demonstrated using babashka for simplicity):
```clojure
; missing name
user=> (doc doc)
-------------------------
clojure.repl/
Macro
nil

; var name string representation is different from the symbol that refers to it
user=> (var thread-bound?)
#'clojure.core/sci-thread-bound?
```

**High-level description of main changes**
- In the `new-var` and family helper functions, assoc `:name` meta onto the meta of the var being created. In case the name passed to `new-var` contains a namespace, strip the namespace off the symbol that goes into the metadata.
- put `:ns` meta on vars being interned (in `sci-intern`), and use the helper function which will also add on the `:name` meta
- Use metadata for producing `SciVar`s symbol and toString and print-method and so on. As a fallback in case there's no `:name` metadata on the var (if a constructor was used without explicitly supplying the appropriate metadata), we can still use the `sym` field.
- There are some cases where we copy vars, but we'd like the target var to have a different name from the source var (this really only affects the metadata and string representations), so what is basically an additional arity has been to `copy-var`. Based on the note about self-hosted CLJS not handling multi-arity macros, I followed the pattern and added a different macro called `copy-and-rename-var` - I'm very open to changing that name (I've already changed it at least twice) based on preference. Because this goes along with `copy-var`, I've also added some documentation and an example to the readme.
- use that macro to rename the vars with different source names (e.g. `'thread-bound?` and `symbol`)
- add a test that confirms that all public vars (minus the protocol-ish ones) have ns and name metadata that matches the ns and symbol names from `(ns-publics)`

**Minor/ancillary changes**
- created some `SciVar`s for things that weren't `SciVar`s
- removed the test call for non-existent performance namespace

I've also run the babashka tests against these changes locally and couldn't find any problems - if this goes through, I'll have a follow on PR for babashka that uses `copy-and-rename-var` to match a handful of var names up with their symbol names.

Please answer the following questions and leave the below in as part of your PR.

- [x] I have read the [developer documentation](https://github.com/babashka/sci/blob/master/doc/dev.md).

- [x] This PR corresponds to an [issue with a clear problem statement](https://github.com/babashka/sci/blob/master/doc/dev.md#start-with-an-issue-before-writing-code).

- [x] This PR contains a [test](https://github.com/babashka/sci/blob/master/doc/dev.md#tests) to prevent against future regressions

### CODE REVIEW

**Comment by borkdude** [comment]
Looking good overall. Any reason to introduce a new function. Perhaps:
``` clojure
(copy-var foo/bar the-sci-ns new-name)
```
could also work?

I noticed some issues with multi-arity macros in self-hosted CLJS, but recently discovered that it was not the multi-arity that was the problem, but it has problems with expanding into something which is not fully qualified already.

**Comment by bobisageek** [comment]
The separate function was purely based on the self-hosted CLJS comment in `sci.impl.namespaces` (I don't do much CLJS, so I would definitely defer to better knowledge). I'll try it out with the arity overload, and this might be as good a time as any to checkout nbb and test the 3-arg `copy-var` from there to ensure that it works as expected in cljs as well.  (I'm very paranoid about breaking builds)

**Comment by borkdude** [comment]
@bobisageek You will notice the self-hosted build fail, don't worry. I can also take that change if you want. Just wondering if you would find that a good API. We could also do `(copy-var var ns {:name ...})` perhaps.

**Comment by bobisageek** [comment]
Ahh... the optional third argument is the API I was originally hoping for, but now that you mention the map, I guess another option (depending on how far we want to go) would be to take an optional map of metadata that we could merge onto the extracted meta (but I might be taking it too far). If you think that might be a nice idea for later on, then I think your idea of taking an options map as the third argument would be a good first step - since `:name` would already be the start of the meta, adding the ability to specify arbitrary metadata later would be a backward-compatible change.

**Comment by borkdude** [comment]
Well, we could always add another arity for that ;) But yeah, adding map seems the way to go. Let's just support `:name` and no other other options, as we can leave room for something else than adding metadata too.

**Comment by bobisageek** [comment]
Well, you were right about self-hosted failing :) is there a quick fix for that? You said something needs to be fully-qualified?

I did run a quick experiment in a local nbb, and that did seem to work without incident (and now I might get addicted to nbb).

**Comment by bobisageek** [comment]
it turns out when I changed the macro to be 3-arity, I messed up on the elided vars scenario, so I pushed a small change to address that

**Comment by borkdude** [comment]
I'll take a look at self-hosted :)

**Comment by borkdude** [comment]
@bobisageek I was wrong, the multi-arity macro is still a problem it seems.

Repro:
https://github.com/babashka/sci/commit/e73377fc37972d0661509a68678961926ba7acf5

I invited you to the #cljs-dev channel to discuss this but maybe we should go with `copy-var+`.

**Comment by borkdude** [comment]
I have a pending fix here:

https://github.com/babashka/sci/pull/710

But CircleCI isn't cooperating.

**Pull request closed without merging**
