### PR TITLE
Bobisageek name metadata

### PR DESCRIPTION
**Pull request by borkdude**
Please answer the following questions and leave the below in as part of your PR.

- [ ] I have read the [developer documentation](https://github.com/babashka/sci/blob/master/doc/dev.md).

- [ ] This PR corresponds to an [issue with a clear problem statement](https://github.com/babashka/sci/blob/master/doc/dev.md#start-with-an-issue-before-writing-code).

- [ ] This PR contains a [test](https://github.com/babashka/sci/blob/master/doc/dev.md#tests) to prevent against future regressions

### CODE REVIEW

**Comment by borkdude** [comment]
@bobisageek I fixed self-hosted per your suggestion and added a Github CI config.

One last thing:

I wonder if we should treat :name as a compile time constant, similar to the first argument:
```
 (sci/copy-var inc nil {:name 'foo})
```
vs:
```
 (sci/copy-var inc nil {:name foo})
```

**Comment by bobisageek** [comment]
Yeah - I have no concerns about pulling out the name at compile time. I think this is quite a cool change.

**Comment by borkdude** [comment]
My question wasn't about that, but thanks :) It was about: should we "eval" `name` at runtime or treat it as a constant (so it doesn't have to be quoted).

**Comment by bobisageek** [comment]
Oh - you're thinking 3 levels above me :)

**Pull request merged**
