### PR TITLE
deftype using reify.

### PR DESCRIPTION
**Pull request by borkdude**

### CODE REVIEW

**Comment by GreshamDanielStephens** [comment]
haven't had a chance to look at this recently I'm afraid.
Shall I try to finish it assuming the same restrictions that reify has now, or do you think it's not going to be useful under those constraints?

**Comment by borkdude** [comment]
@GreshamDanielStephens We can try to make the best of it :)

**Comment by arichiardi** [comment]
Should I rebase this one? I guess I am interested - we are heavy users of HugSQL which uses `deftype` under the hood.

**Comment by borkdude** [comment]
@arichiardi I'm happy to re-consider `deftype` is this enables access to additional libraries. 

But in the case of hugsql, there might be more going on, like the loading of SQL drivers that aren't available in bb and I suppose that will be a blocker.

**Comment by borkdude** [comment]
Btw, I have found HoneySQL to be very helpful lately, I'm porting several of my hugsql queries to that. Not saying you should do that, but at least it also works in bb :).

**Comment by arichiardi** [comment]
> I have found HoneySQL

I am a bit fan but the app I was hired to work on does not think the same. It would be a big refactoring if we did that now.

> But in the case of hugsql, there might be more going on, like the loading of SQL drivers

Yes what I was thinking there was to actually use `maps-of-sqlvec` and pass the sqlvec to the babashka sql wrapper.

**Comment by borkdude** [comment]
@arichiardi Hmm, interesting. I think the only major missing piece might be tools.reader for that. We already have tools.reader in the dependency tree of babashka so it might not much extra space to add it.

**Comment by borkdude** [comment]
@arichiardi Another workaround for now might be to spit out those parsed queries and generate a babashka script from it.

**Comment by borkdude** [comment]
Let's continue the discussion about HugSQL here: https://github.com/babashka/babashka/discussions/945

**Comment by borkdude** [comment]
Deftype is now implement another way

**Pull request closed without merging**
