### PR TITLE
add doc/arglists from clojure.core metadata to sci vars, addresses #822

### PR DESCRIPTION
**Pull request by mhuebert**
This adds metadata from clojure.core in `sci.impl.namespaces`. I've tested in jvm and node; I wasn't able to run the selfhost test on my machine and ran out of time. After this change, only some dynamic vars and `alength` are missing metadata. 

- [x] I have read the [developer documentation](https://github.com/babashka/sci/blob/master/doc/dev.md).

- [x] This PR corresponds to an [issue with a clear problem statement](https://github.com/babashka/sci/blob/master/doc/dev.md#start-with-an-issue-before-writing-code).

- [x] This PR contains a [test](https://github.com/babashka/sci/blob/master/doc/dev.md#tests) to prevent against future regressions

### CODE REVIEW

**Comment by borkdude** [comment]
Just an experiment to see how much this adds to the JS output:

Old:
Screenshot 2022-10-27 at 17 01 04

New:
Screenshot 2022-10-27 at 17 01 13

Self-hosted is failing but so are the native builds due to:

```
Syntax error macroexpanding at (opts.cljc:1:1).
Execution error (IndexOutOfBoundsException) at clojure.asm.MethodWriter/computeMethodInfoSize (MethodWriter.java:2061).
Method code too large!
```

**Comment by mhuebert** [comment]
I re-did this using the existing var-meta implementation from `copy-var`, so less new code and tests are passing now. One debatable bit, is using `(with-meta ~sym ~(var-meta ..))` as a way of passing in the metadata to other functions, this was to avoid a larger refactor with changing arities, etc.

**Comment by borkdude** [comment]
@mhuebert I pushed a workaround to https://github.com/babashka/sci/tree/mhuebert-core-meta2

**Comment by borkdude** [comment]
@mhuebert Also fixed the test: it succeeded when the output was `false` from `eval-string*`.

I think all tests were still failing.

https://github.com/babashka/sci/commit/ee34a57e56d938832b27428653dd6c85bc488624

**Comment by borkdude** [comment]
I have a different (more manual) approach in this branch:

https://github.com/babashka/sci/tree/docstrings-issue-822

The issue there is that cljs resolve on line 91 doesn't work correctly for unqualified symbols.

**Comment by mhuebert** [comment]
@borkdude 🤦‍♂️ thanks for catching the bugs. The clj tests were failing because of a mistake I made in `macrofy` which I've fixed but haven't figured out a good path for the cljs stuff. Will have a look at what you did.

**Comment by mhuebert** [comment]
hey, got the green checkmark with some tweaks:
- Pass `&env` to `cljs-resolve`,
- Try reading doc/arglists from both the return value of `cljs-resolve` & its `:meta`

**Comment by borkdude** [comment]
@mhuebert I think the bug with self-hosted can be "solved" by doing `(when (map? &env) ...)`. See also a `(when (symbol? ...))` check elsewhere in that namespace which satisfies self-hosted. Self-hosted is a bit weird in that a .cljc namespace runs a few times and in one of those passes there are extra arguments passed to a macro, which we can probably just ignore.

**Comment by mhuebert** [comment]
@borkdude I brought in the `usetime` macro from macrovich. Putting all the usages of these macros inside that this lets the selfhost stuff without any extra checks. Self-host tests pass now locally, waiting for ci..

**Comment by borkdude** [comment]
With a few minor modifications, merged to master via other PR. Thanks a lot!

**Pull request closed without merging**
